# Generated by Django 4.0.1 on 2022-01-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='category',
            field=models.CharField(default='Misc.', max_length=256),
        ),
    ]
